name: Develop workflow

on:
  push:
    branches:
      - develop

      # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Build 🔧
        run: |
          yarn install

      - name: Deploy 🚀
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: packages/library/storybook-static
          build_command: yarn build:storybook
