name: Develop workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn build:storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: develop
          FOLDER: packages/library/storybook-static
          CLEAN: true
          TARGET_FOLDER: docs
