# Run tests on library when open new pr to develop
name: PR workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install

      - name: Build production bundle
        run: yarn build

      - name: Test the library
        run: yarn test:library

      - name: Lint the library
        run: yarn lint:library

      - name: prettier the app
        run: yarn prettier:check:library
