name: Release PR and publish workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main

      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Build Packages
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          yarn install
          yarn build:library

      - name: Publish package on NPM 📦
        run: yarn workspace @yoniaiz/library publish --access=public
        if: ${{ steps.release.outputs['packages/library--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
