name: Release Library

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version_bump:
        description: "Version bump type (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      EMAIL: yoni29396@gmail.com
      NAME: yonatanAiz

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build the code
        run: yarn build

      - name: Bump Library Version
        run: |
          git config --global user.email ${{ env.EMAIL }}
          git config --global user.name ${{ env.NAME }}
          yarn workspace library version --new-version ${{ github.event.inputs.version_bump }}
          git push origin HEAD --tags

      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
