name: Release Library

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version_bump:
        description: "Version bump type (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      EMAIL: yoni29396@gmail.com
      NAME: yonatanAiz

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Build the code
        run: yarn build:library

      - name: git auth
        run: |
          git config --global user.email ${{ env.EMAIL }}
          git config --global user.name ${{ env.NAME }}

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: packages/library
        with:
          version-type: ${{ github.event.inputs.version_bump }}

      - name: Publish package on NPM 📦
        run: yarn workspace @yoniaiz/library publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
