name: Release Library

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version_bump:
        description: "Version bump type (patch, minor, major)"
        required: true
        options:
          - patch
          - minor
          - major

env:
  VERSION_BUMP: ${{ inputs.version_bump }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version bump
        run: |
          if [ "$VERSION_BUMP" == "patch" ]; then
            bump=patch
          elif [ "$VERSION_BUMP" == "minor" ]; then
            bump=minor
          elif [ "$VERSION_BUMP" == "major" ]; then
            bump=major
          else
            echo "Invalid version bump option."
            exit 1
          fi

      - name: Bump Library Version
        run: |
          echo $bump
          yarn version --new-version ($bump)
          git push origin HEAD --tags

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: "Release New Version"
          draft: false
          prerelease: fals
