name: Release Library

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version_bump:
        description: "Version bump type (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.TOKEN }}

      - name: Bump Library Version
        run: |
          git config --global user.email "{{ env.EMAIL }}"
          git config --global user.name "{{ env.NAME }}"
          yarn workspace library version --new-version ${{ github.event.inputs.version_bump }}

      - name: Push Changes
        uses: actions/git-client@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: main
          push: true
          force-with-lease: true
          tags: false

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: "Release New Version"
          draft: false
          prerelease: false
